- name: Frontend setup
  hosts: all
  become: true
  tasks:
    - name: Install the Nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Copy expense config file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Delete existing App content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create application directory
      ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

    - name: Download and extract application content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Enable service Nginx
      ansible.builtin.systemd_service:
        name: Nginx
        enabled: true
        state: restarted





















    - name: Enable service httpd and ensure it is not masked
      ansible.builtin.systemd_service:
        name: httpd
        enabled: true
        state: restarted