- name: Disable existing mysql file
  ansible.builtin.shell: dnf module disable mysql -y

- name: Copy mysql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql-community-server -y
  ansible.builtin.dnf:
    name: mysql-community-server
    state: installed

- name: Start mysql Service
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: true
    state: restarted

- name: Set Mysql Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1