format_version: 10
pipelines:
  deploy:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/Tejaswiniallam1/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - dev-stage:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: ls -l
                    run_if: passed
#      - UAT-stage:
#          fetch_materials: true
#          keep_artifacts: false
#          clean_workspace: false
#          approval:
#            type: success
#            allow_only_on_success: false
#          jobs:
#            test-job:
#              timeout: 0
#              tasks:
#                - exec:
#                    command: ls
#                    run_if: passed


