- name: Delete existing App content
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: Download and extract application content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_location }}"
    remote_src: true